spring.application.name=propra2proj
spring.security.oauth2.client.registration.github.client-id=Ov23liIph6V66VAtEf0U
spring.security.oauth2.client.registration.github.client-secret=6f6c1e78031400ef1736aa3b3e5874a4517be0cf
spring.security.oauth2.client.registration.github.scope=read:user


